backend:
  name: github
  repo: uppertoe/handbook
  branch: main
  base_url: https://handbook.anaesdept.org
  auth_endpoint: cms/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Feature Image", name: "featured", widget: "image", required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Hospitals", name: "hospitals", widget: "list", required: false, field: { label: "Hospital", name: "hospital", widget: "string" } }
      - { label: "Tags", name: "tags", widget: "list", required: false, field: { label: "Tag", name: "tag", widget: "string" } }
      - {
          label: "Authors", 
          name: "authors", 
          widget: "relation", 
          collection: "authors", 
          value_field: "file", 
          search_fields: ["name"], 
          display_fields: ["name"], 
          multiple: true,
          required: false
        }
      - { label: "Series", name: "series", widget: "list", required: false, field: { label: "Series", name: "series", widget: "string" } }
      - { label: "Series Order", name: "series_order", widget: "number", value_type: "int", required: false  }

  - name: "authors"
    label: "Authors"
    folder: "data/authors"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text" }
      - {
          label: "Social",
          name: "social",
          widget: "list",
          field: {
            label: "Email",
            name: "email",
            widget: "string",
            pattern: [
              "^mailto:.+@.+\\..+$",  # Regex pattern to match 'mailto:' format
              "Email must be in the form 'mailto:email@example.com'"
            ]
          }
        }
